#!/bin/bash -l
# Bash is needed because we use its "array" data structure
# the -l flag means it will act like a login shell,
# and source the .profile, .bashrc, and so on

# List of all tasks to execute
tasks=(
"python /home/capybara/BayesianHypernet/Active_Learning_Tasks/BHN_AL/dk_AL.py --seed=2 --arch=hyperCNN --acq=bald --num_experiments=1 --coupling=4 --convex_combination=0 --lr0=.001 --new_model=1 --params_reset=deterministic --save=1 --test_eval=1 --save_dir=/rap/jvb-000-aa//capy/results/launch6_dk_AL.py"
)

# Execute the pre tasks
echo '[DBI] executing on host' $HOSTNAME
echo MOAB_JOBNAME=${MOAB_JOBNAME}
echo MOAB_USER=${MOAB_USER}
echo MOAB_TASKMAP=${MOAB_TASKMAP}
echo MOAB_CLASS=${MOAB_CLASS}
echo MOAB_PROCCOUNT=${MOAB_PROCCOUNT}
echo MOAB_GROUP=${MOAB_GROUP}
echo MOAB_NODELIST=${MOAB_NODELIST}
echo MOAB_ACCOUNT=${MOAB_ACCOUNT}
echo MOABHOMEDIR=${MOABHOMEDIR}
echo MOAB_MACHINE=${MOAB_MACHINE}
echo MOAB_NODECOUNT=${MOAB_NODECOUNT}
echo MOAB_JOBID=${MOAB_JOBID}
echo MOAB_QOS=${MOAB_QOS}
echo MOAB_PARTITION=${MOAB_PARTITION}

# Execute the task
${tasks[$MOAB_JOBARRAYINDEX]}
